source 'https://rubygems.org'

# Specify your gem's dependencies in new-york-reader.gemspec
gemspec
gem 'nokogiri'
gem 'pry'
gem 'open-uri'
gem 'require_all'
gem 'launchy', '~> 2.4', '>= 2.4.3'
gem 'ruby-progressbar', '~> 1.8', '>= 1.8.1'
gem 'command_line_reporter'
gem 'colored', '~> 1.2'
